# TADS 3 makefile

-I /usr/local/share/frobtads/tads3/include/
-I /usr/local/share/frobtads/tads3/lib/
-I /usr/local/share/frobtads/tads3/lib/adv3Lite
-I /usr/local/share/frobtads/tads3/lib/adv3Lite/english
-we
-pre
-D LANGUAGE=english
-Fy obj
-Fo obj
-v
-w1
-Fs ../
-o tests.t3
-d

##sources
-lib system
-lib adv3Lite/adv3Lite
-lib ../cartographer
-source ../renderers/scalable-text-renderer
-source runner
-source unittest
-source tilemap-tests
-source generateSquare-tests

-res
GameInfo.txt
